swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
  - https
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - TRANSACTION Module
      summary: User accounts 
      description: User's account list 
      #produces:
       # - application/json
      responses:
        '200':
          description: user's accounts recovered successfully
          schema:
            $ref: '#/definitions/UserAccount'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /user/accounts/{accountID}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - TRANSACTION Module
      summary: Transactions of a users's account
      description: User's account transaction list
      parameters:
        - in: path
          name: accountID
          description: ID of the user's account
          required: true
          type: string
      produces:
        - application/json      
      responses:
        '200':
          description: User transactions recovered successfully 
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Unauthorized
        '500':
          description: Internal Server Error 
  /user/accounts/{accountID}/transactions/{transactionID}/category:
    put:
      security:
        - Bearer: []
      tags:
        - TRANSACTION Module
      summary: Edit Category of a Transaction
      description: edit the category of a user's transaction by transactionID
      parameters:
        - name: accountID
          in: path
          required: true
          description: ID of the user's account
          type: string
        - name: transactionID
          in: path
          required: true
          description: ID of the user's transaction
          type: string
        - name: body
          in: body
          description: Category 
          required: true
          schema:
            $ref: '#/definitions/Category'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction category edited successfully 
        '400':
          description: Unauthorized
        '500':
          description: Internal Server Error


  /user/accounts/{accountID}/transactions/{transactionID}/note:
    put:
      security:
        - Bearer: []
      tags:
        - TRANSACTION Module
      summary: Edit Note of a Transaction
      description: Edit the note of a transaction by transactionID
      parameters:
        - name: accountID
          in: path
          required: true
          description: ID of the user's account
          type: string
        - name: transactionID
          in: path
          required: true
          description: ID of the user's account transaction
          type: string
        - name: body
          in: body
          description: Note
          required: true
          schema:
            $ref: '#/definitions/Note'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction note edited successfully
        '400':
          description: Unauthorized
        '500':
          description: Internal Server Error 
    delete:
      security:
        - Bearer: []
      tags:
        - TRANSACTION Module
      summary: Delete a Transaction note
      description: Remove transaction note from a user's account by transactionID
      parameters:
        - name: accountID
          in: path
          required: true
          description: ID of the user's account
          type: string
        - name: transactionID
          in: path
          required: true
          description: ID of the user's transaction
          type: string
      responses:
        '200':
          description: Transaction note deleted successfully
        '400':
          description: Unauthorized
        '500':
          description: Internal Server Error         
          
 
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  UserAccount:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        amount:
          type: string
        description:
          type: string
  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
      description:
        type: string
      amount:
        type: string
      balance:
        type: string
      transaction_type:
        type: string
      category:
        type: string
      note:
        type: string
  Category:
    properties:
      category:
        type: string
        description: transaction category              
  Note:
    properties:
      note:
        type: string
        description: transaction note 