swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Possible API endpoints for phase 2 of Argent Bank project / Transactions
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /user/transactions/month:
    get:
      tags:
        - TRANSACTIONS Module
      summary: Get user's transactions for a specific month
      description: Retrieve every transactions of user for a month
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer by Json Web token
          required: true
          type: string
        - name: Month
          in: header
          description: Attach Bearer by Json Web token
          required: true
          type: integer
          format: int32
          minimum: 1
          maximum: 12
      produces:
        - application/json
      responses:
        '200':
          description: user transactions retrieved Successfully for a month
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid month provided
        "401":
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

  /user/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - TRANSACTIONS Module
      summary: Get transaction details
      description: Get specific transactions info
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer by Json Web token
          required: true
          type: string
        - name: transactionId
          in: path
          description: ID of the transaction
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: transaction information retrieved successfully retrieved
          schema:
            $ref: '#/definitions/userTransaction'
        '400':
          description: Invalid Fields 
        "401":
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - TRANSACTIONS Module 
      summary: Update the transactions infos
      description: Modify the transactions infos
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer by Json Web token
          required: true
          type: string
        - name: transactionId
          in: path
          description: ID of the transaction
          required: true
          type: integer
        - name: body
          in: body
          description: transaction update
          required: true
          schema:
            $ref: '#/definitions/TransactionInfo'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction's infos updated successfully
          schema:
            $ref: '#/definitions/editTransaction'
        '400':
          description: Invalid Fields
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

    
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transactions:
    type: object
    properties:
      id_transaction:
        type: number
        description: transaction unique id
      transactionType:
        type: string
        description: transaction type
      category:
        type: string
        description: category of the transaction
      notes:
        type: string
        description: any relevant note user want to add
  userTransaction:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
        example: User transaction retrieved succesfully
      body:
        type: array
        items:
          $ref: '#/definitions/Transactions'  
  editTransaction:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
        example: User transaction updated succesfully
      body:
        type: array
        items:
          $ref: '#/definitions/Transactions'
  TransactionInfo:
    properties:
      transactionType:
        type: string
        description: transaction type
      category:
        type: string
        description: category of the transaction
      notes:
        type: string
        description: note of  the transaction
